package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// Messages processed counter
	messagesProcessed = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_messages_processed_total",
			Help: "Total number of market data messages processed",
		},
		[]string{"exchange", "symbol"},
	)

	// Processing latency histogram
	processingLatency = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "crypto_stream_processing_latency_seconds",
			Help:    "Time taken to process a single tick",
			Buckets: prometheus.ExponentialBuckets(0.000001, 2, 20), // 1μs to ~1s
		},
	)

	// Active workers gauge
	activeWorkers = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crypto_stream_active_workers",
			Help: "Number of active worker goroutines",
		},
	)

	// Alerts generated counter
	alertsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_alerts_generated_total",
			Help: "Total number of alerts generated by type",
		},
		[]string{"type", "severity"},
	)

	// WebSocket connections gauge
	wsConnections = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crypto_stream_websocket_connections",
			Help: "Number of active WebSocket connections to exchanges",
		},
	)

	// Channel buffer utilization
	channelUtilization = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crypto_stream_channel_utilization_percent",
			Help: "Percentage of channel buffer currently in use",
		},
		[]string{"channel_type"},
	)

	// Dropped messages (backpressure indicator)
	droppedMessages = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_dropped_messages_total",
			Help: "Number of messages dropped due to channel overflow",
		},
		[]string{"reason"},
	)
)

// IncrementMessagesProcessed increments the message counter
func IncrementMessagesProcessed(exchange, symbol string) {
	messagesProcessed.WithLabelValues(exchange, symbol).Inc()
}

// RecordProcessingLatency records a processing duration
func RecordProcessingLatency(seconds float64) {
	processingLatency.Observe(seconds)
}

// SetActiveWorkers sets the number of active workers
func SetActiveWorkers(count int) {
	activeWorkers.Set(float64(count))
}

// IncrementAlertsGenerated increments alert counter
func IncrementAlertsGenerated(alertType, severity string) {
	alertsGenerated.WithLabelValues(alertType, severity).Inc()
}

// IncrementWSConnections increments WebSocket connection count
func IncrementWSConnections() {
	wsConnections.Inc()
}

// DecrementWSConnections decrements WebSocket connection count
func DecrementWSConnections() {
	wsConnections.Dec()
}

// SetChannelUtilization sets channel buffer usage percentage
func SetChannelUtilization(channelType string, percent float64) {
	channelUtilization.WithLabelValues(channelType).Set(percent)
}

// IncrementDroppedMessages increments dropped message counter
func IncrementDroppedMessages(reason string) {
	droppedMessages.WithLabelValues(reason).Inc()
}
