package metrics

import (
	"sync"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// Messages processed counter
	messagesProcessed = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_messages_processed_total",
			Help: "Total number of market data messages processed",
		},
		[]string{"exchange", "symbol"},
	)

	// Processing latency histogram
	processingLatency = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "crypto_stream_processing_latency_seconds",
			Help:    "Time taken to process a single tick",
			Buckets: prometheus.ExponentialBuckets(0.000001, 2, 20), // 1μs to ~1s
		},
	)

	// Active workers gauge
	activeWorkers = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crypto_stream_active_workers",
			Help: "Number of active worker goroutines",
		},
	)

	// Alerts generated counter
	alertsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_alerts_generated_total",
			Help: "Total number of alerts generated by type",
		},
		[]string{"type", "severity"},
	)

	// WebSocket connections gauge
	wsConnections = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crypto_stream_websocket_connections",
			Help: "Number of active WebSocket connections to exchanges",
		},
	)

	// Channel buffer utilization
	channelUtilization = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crypto_stream_channel_utilization_percent",
			Help: "Percentage of channel buffer currently in use",
		},
		[]string{"channel_type"},
	)

	// Dropped messages (backpressure indicator)
	droppedMessages = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crypto_stream_dropped_messages_total",
			Help: "Number of messages dropped due to channel overflow",
		},
		[]string{"reason"},
	)

	messagesProcessedCache  sync.Map
	alertsGeneratedCache    sync.Map
	droppedMessagesCache    sync.Map
	channelUtilizationCache sync.Map
)

// IncrementMessagesProcessed increments the message counter
func IncrementMessagesProcessed(exchange, symbol string) {
	key := exchange + "\x00" + symbol
	counter, ok := messagesProcessedCache.Load(key)
	if !ok {
		created, _ := messagesProcessedCache.LoadOrStore(key, messagesProcessed.WithLabelValues(exchange, symbol))
		counter = created
	}
	counter.(prometheus.Counter).Inc()
}

// RecordProcessingLatency records a processing duration
func RecordProcessingLatency(seconds float64) {
	processingLatency.Observe(seconds)
}

// SetActiveWorkers sets the number of active workers
func SetActiveWorkers(count int) {
	activeWorkers.Set(float64(count))
}

// IncrementAlertsGenerated increments alert counter
func IncrementAlertsGenerated(alertType, severity string) {
	key := alertType + "\x00" + severity
	counter, ok := alertsGeneratedCache.Load(key)
	if !ok {
		created, _ := alertsGeneratedCache.LoadOrStore(key, alertsGenerated.WithLabelValues(alertType, severity))
		counter = created
	}
	counter.(prometheus.Counter).Inc()
}

// IncrementWSConnections increments WebSocket connection count
func IncrementWSConnections() {
	wsConnections.Inc()
}

// DecrementWSConnections decrements WebSocket connection count
func DecrementWSConnections() {
	wsConnections.Dec()
}

// SetChannelUtilization sets channel buffer usage percentage
func SetChannelUtilization(channelType string, percent float64) {
	gauge, ok := channelUtilizationCache.Load(channelType)
	if !ok {
		created, _ := channelUtilizationCache.LoadOrStore(channelType, channelUtilization.WithLabelValues(channelType))
		gauge = created
	}
	gauge.(prometheus.Gauge).Set(percent)
}

// IncrementDroppedMessages increments dropped message counter
func IncrementDroppedMessages(reason string) {
	counter, ok := droppedMessagesCache.Load(reason)
	if !ok {
		created, _ := droppedMessagesCache.LoadOrStore(reason, droppedMessages.WithLabelValues(reason))
		counter = created
	}
	counter.(prometheus.Counter).Inc()
}
